[package]
name = "hypher-rs"
version = "1.0"
authors = ["Chilli <chilli@thechilli.dev"]
license = "MPL-2.0"
repository = "https://github.com/TheChilliPL/hypher-rs"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
hypher = "0.1"
